### ISSUE TITLE
 only starts 2 servers.

### ISSUE THREAD

**Issue by arodrime** [rustyrazorblade/easy-cass-lab#145]
Following the readme instruction, when I run `easy-cass-lab start` I have the following output from all nodes:
```
ubuntu@cassandra0:~$ nodetool status
Datacenter: us-east-1
=====================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address     Load        Tokens  Owns (effective)  Host ID                               Rack      
UN  10.0.0.18   114.45 KiB  4       100.0%            44b3b941-7d00-40a8-b67d-7ae6dd55730d  us-east-1d
UN  10.0.2.230  114.43 KiB  4       100.0%            9ef66c1c-dc9c-4278-a64d-57cf860a08ab  us-east-1c
```

Looking at the logs I see this kind of warning.

```
WARN  [main] 2024-05-21 09:52:39,573 TokenMetadata.java:233 - Token 6860648722076612849 changing ownership from /10.0.1.169:7000 to /10.0.2.230:7000
WARN  [main] 2024-05-21 09:52:39,573 TokenMetadata.java:233 - Token -4703394666759391058 changing ownership from /10.0.1.169:7000 to /10.0.2.230:7000
WARN  [main] 2024-05-21 09:52:39,573 TokenMetadata.java:233 - Token 2338211983527944886 changing ownership from /10.0.1.169:7000 to /10.0.2.230:7000
WARN  [main] 2024-05-21 09:52:39,574 TokenMetadata.java:233 - Token -3163046486698489243 changing ownership from /10.0.1.169:7000 to /10.0.2.230:7000
```

It seems that 2 nodes are fighting for the same token range. To fix that I stopped C* and cleared the all the data on one of the conflicting nodes, remove it from the seeds in `cassandra.yaml` and started it again.

The 3 nodes being created are configured as seeds, it seems that for some reason using C*5-beta-1 it lead to 2 of the nodes fighting for ownership of the same token ranges.

**Comment by rustyrazorblade** [comment]
I've seen this happen several times. Unfortunately different nodes will have a different perspective of the cluster sometimes too. 

I think the only sane fix is to use a single seed.

**Comment by rustyrazorblade** [comment]
I pushed up the fix to use a single seed in b3c0c059d6abfd20182972f04590056c06fc9e39

**Comment by arodrime** [comment]
Nice! Looks good. I believe this will help to get a consistent bootstrap.

The only things that comes to mind that could still go wrong is if the first node created by terraform is not the seed node. I don't know if terraform allows you to choose in which order nodes are added, if there are retries. I don't know if this is a real problem or not.

**Comment by arodrime** [comment]
I can rebuild the image to test it and see what this change brings :).

**Comment by rustyrazorblade** [comment]
There's no need to rebuild the entire image.  You can run `./gradlew shadowjar installdist`.

Rebuilding the image is only needed if there's changes to the packer image.

**Comment by arodrime** [comment]
Oh, that's nice, it's faster. Thanks!

Hum it seems there is something still going wrong, c1 and c2 are still fighting fo specific tokens.

```
ERROR [main] 2024-05-21 15:37:01,268 CassandraDaemon.java:877 - Exception encountered during startup
java.lang.RuntimeException: Bootstrap Token collision between /10.0.1.146:7000 and /10.0.2.209:7000 (token 1447118629129762438
	at org.apache.cassandra.locator.TokenMetadata.addBootstrapTokens(TokenMetadata.java:372)
	at org.apache.cassandra.locator.TokenMetadata.addBootstrapTokens(TokenMetadata.java:354)
	at org.apache.cassandra.service.StorageService.handleStateBootstrap(StorageService.java:3031)
	at org.apache.cassandra.service.StorageService.onChange(StorageService.java:2712)
	at org.apache.cassandra.gms.Gossiper.doOnChangeNotifications(Gossiper.java:1777)
	at org.apache.cassandra.gms.Gossiper.addLocalApplicationStateInternal(Gossiper.java:2175)
	at org.apache.cassandra.gms.Gossiper.addLocalApplicationStates(Gossiper.java:2190)
	at org.apache.cassandra.service.StorageService.bootstrap(StorageService.java:2108)
	at org.apache.cassandra.service.StorageService.joinTokenRing(StorageService.java:1249)
	at org.apache.cassandra.service.StorageService.joinTokenRing(StorageService.java:1209)
	at org.apache.cassandra.service.StorageService.initServer(StorageService.java:988)
	at org.apache.cassandra.service.StorageService.initServer(StorageService.java:905)
	at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:377)
	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:721)
	at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:855)
INFO  [StorageServiceShutdownHook] 2024-05-21 15:37:01,278 HintsService.java:235 - Paused hints dispatch
```

And:

```
Datacenter: us-east-1
=====================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address     Load        Tokens  Owns (effective)  Host ID                               Rack
UN  10.0.1.146  119.48 KiB  4       100.0%            e22f0f9d-8fe3-4a45-88d7-f36fe4a81d8e  us-east-1b
UN  10.0.0.89   119.58 KiB  4       100.0%            baef5076-6567-4f21-ba2b-37cb9fcb205c  us-east-1d
```

**Comment by rustyrazorblade** [comment]
Ugh.  As a workaround, when you run `start`, pass `--sleep 120` for it to sleep 2 minutes in between starting nodes.  There's something pretty broken in C*'s startup sequence.

I can't remember offhand what the startup sequence is (it's probably just whatever order is in the `tfstate` file, but you should see it in the output when you run the command.  The instances are all created in their own VPC, with 3 subnets.  The IP address should tell you which subnet it is.  Check the seeds list in the generated cassandra.patch.yaml to see if that's the first node that starts up.  If the seed is first to start and the other two nodes join in a staggered fashion, then it's definitely worth leaving a comment on https://issues.apache.org/jira/browse/CASSANDRA-16364 with what you've seen.

**Comment by rustyrazorblade** [comment]
I've pushed up c326fafc3b250e40fd063611f5013840719b5e6f which changes the default sleep time from 30 seconds to 2 minutes.  I'll do a follow up to ensure the seed nodes are started first.

**Comment by arodrime** [comment]
Hi, it looks like the sleep 120 was enough (or I got lucky? :)).

```
$ nodetool status
Datacenter: us-east-1
=====================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address     Load        Tokens  Owns (effective)  Host ID                               Rack      
UN  10.0.0.172  119.59 KiB  4       60.8%             09fe19ca-4818-478a-9ac7-a07128a171bc  us-east-1d
UN  10.0.1.246  84.85 KiB   4       58.2%             9b0841ba-074d-4531-bde0-36a6ef0d569b  us-east-1b
UN  10.0.2.73   84.85 KiB   4       81.0%             c9941807-af51-4d54-a688-f3ba1d3b1f71  us-east-1c
```

Thanks!

**Comment by arodrime** [comment]
I also confirm my seed started first, then the 2 nodes other joined one by one (as expected) with no troubles this time.
I'm ok with this change I would say. Feel free to close the ticket if you'd like :).
