### ISSUE TITLE
cqlsh not working

### ISSUE THREAD

**Issue by rustyrazorblade** [rustyrazorblade/easy-cass-lab#34]
Just ran into this when trying to use cqlsh after `sudo use-cassandra 4.1`

```
ubuntu@ip-172-31-44-65:~$ cqlsh
Traceback (most recent call last):
  File "/usr/local/cassandra/4.1/bin/cqlsh.py", line 134, in <module>
    from cassandra.cluster import Cluster
  File "/usr/local/cassandra/4.1/bin/../lib/cassandra-driver-internal-only-3.25.0.zip/cassandra-driver-3.25.0/cassandra/cluster.py", line 33, in <module>
ModuleNotFoundError: No module named 'six.moves'
```

**Comment by jrwest** [comment]
Fixed in `931a9b13c7461dfb33b67c21b36f103a22196890`
